= Home Office Setup

Smart Step Supreme Polyurethane Anti-Fatigue Mat with Dual Gripper System, 30" x 18", Black

Electric Adjustable Height Workstation Desk 24" x 60"

Targus - Chill Mat+ Laptop Cooling System with 4-Port USB Hub

Logitech Wireless Gaming Headset G930 with 7.1 Surround Sound

Serta 44187 Back in Motion Health and Wellness Mid-Back Office Chair, Frye Chocolate

iBuyPower Battalion 101 W650SJ Gaming Laptop

- Battalion 101 W650SJ 15.6" Full HD 1920x1080 LED-Backlit Display Laptop
- Intel® Core™ i7-4700MQ Mobile Processor (4x 2.4GHz/6MB L3 Cache)
- 16GB [8GB x 2] 1600MHz DDR3 SO-DIMM Laptop Memory
- NVIDIA GeForce GT 850M 2GB GDDR3 Video w/ NVIDIA Optimus [W650SJ]
- 512 GB ADATA SX900 SSD -- Read: 540MB/s, Write: 465MB/s - Single Drive
- 8x Dual Format DVD±R/±RW + 16x CD-R/RW Combo Drive [W650SJ]
- Built-in 9-in-1 Media Card Reader/Writer [Laptop]
- 3D Premium Surround Sound Onboard
- Built-in 10/100/1000 Mbps LAN [Laptop]
- 802.11 b/g/n Wi-Fi + Bluetooth Combo [W650SJ]
- Windows 10
- Built-in 2x USB 2.0 + 2x USB 3.0 + 1x USB 3.0 / eSATA Combo Ports [Laptop]
- GWC Tech USB 3.0 Docking Station w/ USB 3.0, Audio, HDMI, DVI, RJ45 Connectors